apiVersion: v1
kind: Service
metadata:
  name: helloautoscaler
  labels:
    app: helloautoscaler
spec:
  selector:
    app: helloautoscaler
  ports:
  - port: 8080
    protocol: TCP
    nodePort: 30001
  type: LoadBalancer